on: [push]

name: Test Action

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    name: Test the action
    steps:
      - uses: actions/checkout@v2
      - name: Setup PDM
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm install -v

      - name: Verify python version
        run: python test.py
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
